ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/*"
          - ".github/*.yml"
rust:
  - changed-files:
      - any-glob-to-any-file:
          - "src/*"
          - "src/**/*"
protobuf:
  - changed-files:
      - any-glob-to-any-file:
          - "proto/*"
          - "proto/**/*"
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/ISSUE_TEMPLATE/*"
          - "pull_request_template.md"
data:
  - changed-files:
      - any-glob-to-any-file:
          - "*.csv"
