ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/*"
          - ".github/*.yml"
rust:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
          - "stationapi/**"
          - "preprocessor/**"
          - "data_validator/**"
          - "build.rs"
graphql:
  - changed-files:
      - any-glob-to-any-file:
          - "schema/**"
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/ISSUE_TEMPLATE/*"
          - "pull_request_template.md"
data:
  - changed-files:
      - any-glob-to-any-file:
          - "*.csv"
deploy-prod:
  - base-branch: ["^master$"]
deploy-dev:
  - base-branch: ["^dev$"]