FROM rust:1
WORKDIR /app
RUN apt-get update && \
    apt-get install -y --quiet protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*
COPY . .
RUN cargo install cargo-watch
ENV PORT 50051
EXPOSE $PORT
CMD ["./stationapi"]
