name: stationapi

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.dev
    command: cargo watch -s "cargo run -p stationapi"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://stationapi:password@db/stationapi
      ACCEPT_HTTP1: true
      ENABLE_ALL_STATIONS_RPC: true
      HOST: 0.0.0.0
    ports:
      - 50051:50051
    networks:
      - sapi-link

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: stationapi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stationapi
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=ja_JP.UTF8 --no-locale
    ports:
      - 5432:5432
    networks:
      - sapi-link

  migration:
    build:
      context: .
      dockerfile: ./docker/migration/Dockerfile
    command: ["./wait-for-it.sh", "db:5432", "--", "./migration"]
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: stationapi
      POSTGRES_DB: stationapi
      PGPASSWORD: password
    networks:
      - sapi-link

networks:
  sapi-link:
