#!/bin/bash
mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -S$MYSQL_SOCKET -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE} /*\!40100 DEFAULT CHARACTER SET utf8 */;"
mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -S$MYSQL_SOCKET $MYSQL_DATABASE < ./migrations/create_table.sql
mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -S$MYSQL_SOCKET $MYSQL_DATABASE < ./tmp.sql
