global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "stationapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:50052"]
        labels:
          service: "stationapi"
